### PR TITLE
Adding tags into the suites/tests from config file

### PR DESCRIPTION
**Pull request by fasterfish**
This is my first pull request. Please don't judge me too harshly.

### CODE REVIEW

**Comment by nvborisenko** [comment]
In config the tags are only for launch, not for suites or tests.
If you want add tags for tests you can use [Category](https://github.com/nunit/docs/wiki/Category-Attribute) attribute for tests. Extension adds categories as tags.

**Comment by fasterfish** [comment]
Yes, but, for example, I want to run a lot of tests on different operating systems, with the same build of the product. I imagined it as follows:
1. I run tests on different platforms, separated by characteristic tags for each of the platforms.
2. In the portal, I would have merge all received launches to after that remained in the tests Information about the system on which tests was runned.

**Comment by nvborisenko** [comment]
It is not yet documented but you are able to customize the Report Portal agent.

Please see the example: https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortalCustomization/Customization.cs

Shortly:

1. Create class, inherit from ITestEventListener
2. Include your dll in *.addins file
3. Subscribe on ReportPortalListener events
4. Modify requests in real-time

Example project contains the following customization:
1. Don't report "Example.dll" suite
2. Add OS Version to the description of launch, and custom tag into launch

Using the same approach you can add OS Version to any item (suite, test, step etc).

**Comment by fasterfish** [comment]
OK thank you very much.
I have one more question on this topic: Is there a similar example for specflow?

**Comment by nvborisenko** [comment]
Search for example-net-specflow repository. I am afraid this example doesn't contain agent customization. Please open another issue there if it is true.

**Pull request closed without merging**
