### PR TITLE
Refactoring approach of handling test item attributes and properties. Re-written approach of processing report items.

### PR DESCRIPTION
**Pull request by AngryTester95**
1. Refactored code in whole project (moving common logic to separate methods, making method more shorter and readable).
2. Implemented attribute and property handlers for test items.
3. Re-written approach of matching report items and handling methods by implementing `ReportKeyAttribute` and matching keys and methods via reflection.

### CODE REVIEW

**Comment by nvborisenko** [comment]
Thanks for that. During the years the code was growing and finally you are a man who started to refactor it.

Only one comment for now: do not use reflection, all types are well known at build phase, we don't expect to handle them at runtime. Less elegant, but at least it doesn't affect user in terms of performance. The same for regex.

Again thanks.

**Comment by AngryTester95** [comment]
> Thanks for that. During the years the code was growing and finally you are a man who started to refactor it.
> 
> Only one comment for now: do not use reflection, all types are well known at build phase, we don't expect to handle them at runtime. Less elegant, but at least it doesn't affect user in terms of performance. The same for regex.
> 
> Again thanks.

@nvborisenko I got your point. No problem, I'll re-write logic with reflection and regex. I just thought that it won't be any performance issue related with reflection due to fact, that it will be invoked once: during ReportPortalListener type initialization and instance initialization (if I'm not mistaken only one instance of ReportPortalListener class will be created by NUnit engine. But I again, I'll re-write this logic with avoiding using reflcetion and regex.

**Comment by AngryTester95** [comment]
> Thanks for that. During the years the code was growing and finally you are a man who started to refactor it.
> 
> Only one comment for now: do not use reflection, all types are well known at build phase, we don't expect to handle them at runtime. Less elegant, but at least it doesn't affect user in terms of performance. The same for regex.
> 
> Again thanks.

@nvborisenko I got your point. No problem, I'll re-write logic with reflection and regex. I just thought that it won't be any performance issue related with reflection due to fact, that it will be invoked once: during ReportPortalListener type initialization and instance initialization (if I'm not mistaken only one instance of ReportPortalListener class will be created by NUnit engine. But I again, I'll re-write this logic with avoiding using reflcetion and regex.

**Comment by nvborisenko** [comment]
I  close this PR with no action. This is big change (not big, but hard to verify), let's make smaller continuous changes, it will be easier to review/accept.

**Pull request closed without merging**
